apiVersion: v1
kind: Secret
metadata:
  name: postgresconf
type: Opaque
data:
  PGRST_JWT_SECRET: MGFjMjQwODdhOTZjNDI3YWI4YTExNWUyOWRjYzY0MWE=
  PGRST_DB_URI: cG9zdGdyZXM6Ly9hdXRoZW50aWNhdG9yOm15c2VjcmV0cGFzc3dvcmRAcG9zdGdyZXMtc2VydmljZTo2NTQzMi9sZWFmdGl4ZGI=
  PGRST_DB_SCHEMA: cHVibGlj
  PGRST_DB_ANON_ROLE: d2ViX2Fub24= #In production this role should not be the same as the one used for the connection
  PGRST_SERVER_PROXY_URI: aHR0cDovLzEyNy4wLjAuMTozMDAw
  request.jwt_web_anon: d2ViX2Fub24=

# CONVERTER DADOS PARA BASE64 echo -n 'admin' | base64
#  DESCONVERTER DADOS DE BASE 64 echo 'MWYyZDFlMmU2N2Rm' | base64 --decode
# PGRST_DB_URI postgresql: postgresql://apiuserleaftixdb:apiuserleaftixdbpassword@postgres-service:65432/leaftixdb
# PGRST_JWT_SECRET 0ac24087a96c427ab8a115e29dcc641a
# PGRST_DB_SCHEMA: public
# ANON_ROLE anon
# PGRST_SERVER_PROXY_URI: http://127.0.0.1:3000

# db-uri = "postgres://authenticator:mysecretpassword@postgres-service:65432/leaftixdb"
# db-schema = "api"
# db-anon-role = "web_anon"