apiVersion: v1
kind: Secret
metadata:
  name: postgresconf
type: Opaque
data:
  PGRST_JWT_SECRET: MGFjMjQwODdhOTZjNDI3YWI4YTExNWUyOWRjYzY0MWE=
  PGRST_DB_URI: cG9zdGdyZXNxbDovL2FwaXVzZXJsZWFmdGl4ZGI6YXBpdXNlcmxlYWZ0aXhkYnBhc3N3b3JkQHBvc3RncmVzLXN2Yy9sZWFmdGl4ZGI=
  PGRST_DB_SCHEMA: cHVibGlj
  PGRST_DB_ANON_ROLE: YW5vbg== #In production this role should not be the same as the one used for the connection
  PGRST_SERVER_PROXY_URI: aHR0cDovLzEyNy4wLjAuMTozMDAw

# CONVERTER DADOS PARA BASE64 echo -n 'admin' | base64
#  DESCONVERTER DADOS DE BASE 64 echo 'MWYyZDFlMmU2N2Rm' | base64 --decode
# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgresconf
# type: Opaque
# stringData:
#   config.yaml: |
#     db-uri: "postgresql://apiuserleaftixdb:apiuserleaftixdbpassword@postgres-svc/leaftixdb"
#     db-schema: "public"
#     db-anon-role: "anon"
#     jwt-secret: "0ac24087a96c427ab8a115e29dcc641a"