kind: StorageClass
#apiVersion: storage.k8s.io/v1 #minikube
apiVersion: storage.k8s.io/v1 #microk8s
metadata:
  namespace: leaftix
  name: pgadmin-std
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists

#provisioner: k8s.io/minikube-hostpath minikube
provisioner: microk8s-hostpath #microk8s

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-pv
  labels:
    app: pgadmin
    type: local
spec:
  storageClassName: pgadmin-std
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/g/leaftix/bd"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pv-claim
  labels:
    app: pgadmin
spec:
  storageClassName: pgadmin-std
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-cfg
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB",
           "Group": "Servers",
           "Port": 31518,
           "Username": "amazinguser",
           "Host": "",
           "SSLMode": "prefer",
           "MaintenanceDB": "awesomedb"
         }
       }
   }

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: web
spec:
 serviceName: "pgadmin-svc"
 podManagementPolicy: Parallel
 replicas: 3
 updateStrategy:
   type: RollingUpdate
 selector:
   matchLabels:
     app: pgadmin
 template:
   metadata:
     labels:
       app: pgadmin
   spec:
     terminationGracePeriodSeconds: 10
     containers:
       - name: pgadmin
         image: dpage/pgadmin4:5.4
         imagePullPolicy: Always
         env:
         - name: PGADMIN_DEFAULT_EMAIL
           value: rondweb@gmail.com
         - name: PGADMIN_DEFAULT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: pgadmin
               key: PGADMIN_PASSWORD
         ports:
         - name: web
           containerPort: 80
         volumeMounts:
         - name: www
           mountPath: /pgadmin4/servers.json
           subPath: servers.json
           readOnly: true
         - name: pgadmin-pv
           mountPath: /var/lib/pgadmin
     volumes:
     - name: pgadmin-pv
       persistentVolumeClaim:
         claimName: pgadmin-pv-claim
     - name: www
       configMap:
         name: pgadmin-cfg

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: pgadmin
