apiVersion: v1
kind: Namespace
metadata:
  name: dotnetcore
  namespace: dotnetcore
  annotations:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapiapp
  namespace: dotnetcore
  labels:
    app: webapiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapiapp
  template:
    metadata:
      labels:
        app: webapiapp
    spec:
      containers:
      - name: webapiapp
        image: rondweb/dotnetcore:webapi
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapiapp-service
  namespace: dotnetcore
spec:
 type: LoadBalancer
 ports:
 - port: 80
 selector:
   app: webapiapp

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapiapp-ingress
  namespace: dotnetcore
  labels:
    app: webapiapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: webapiapp-service
          servicePort: 80          