kind: StorageClass
#apiVersion: storage.k8s.io/v1 #minikube
apiVersion: storage.k8s.io/v1 #microk8s
metadata:
  namespace: leaftix
  name: postgres-std
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists

#provisioner: k8s.io/minikube-hostpath minikube
provisioner: microk8s-hostpath #microk8s

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: postgres-std
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "G:/leaftix/bd"
    path: "/g/leaftix/bd"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: postgres-std
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfg
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: perfectpassword
  PGDATA: /var/lib/postgresql/data/pgdata

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-stf
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: rondweb/postgis:pg14_pgis31
        imagePullPolicy: Always
        # command: ["/bin/sh","-c"]
        # args: ["sleep 99d;"]
        envFrom:
        - configMapRef:
            name: postgres-cfg
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc-ldb
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432    
      targetPort: 15432          
      nodePort: 30000
