# kubectl create clusterrole service-reader -n kube-system --verb=get,list,watch,create,update,patch,delete --resource=services,pods,pods/exec
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: leaftix
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods", "pods/exec"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: leaftix
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
