kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: leaftix
  name: admin-ns
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods", "pods/exec"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admn-ns-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: adm-leaftix
    # Reference to upper's `metadata.namespace`
    namespace: leaftix
roleRef:
  kind: ClusterRole
  name: adm-leaftixr
  apiGroup: rbac.authorization.k8s.io
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adm-leaftix
  namespace: leaftix
automountServiceAccountToken: true
