kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #namespace: leaftix
  namespace: default
  name: admin-ns-leaftix
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods", "pods/exec"]
  verbs: ["get", "watch", "list","create", "update", "patch", "delete"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: adm-ns-rbac
# subjects:
#   - kind: ServiceAccount
#     # Reference to upper's `metadata.name`
#     name: adm-leaftix
#     # Reference to upper's `metadata.namespace`
#     namespace: leaftix
# roleRef:
#   kind: ClusterRole
#   name: admin-ns-leaftix
#   apiGroup: rbac.authorization.k8s.io

#default scheme
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adm-ns-rbac-default
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: adm-leaftix
    # Reference to upper's `metadata.namespace`
    # namespace: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adm-leaftix
  # namespace: leaftix
  namespace: default
automountServiceAccountToken: true
